### ISSUE TITLE
import torchcraft as tc

### ISSUE THREAD

**Issue by ChobitsTheZero** [TorchCraft/TorchCraft#302]
Been trying to run the python example, however when trying to run the script I recieve the following error.

C:\Users\EmilN>C:\Python\Python37-32\python.exe D:\AI\Starcraft\Starcraft2013\TorchCraft\examples\py\example.py -t IP
Traceback (most recent call last):
  File "D:\AI\Starcraft\Starcraft2013\TorchCraft\examples\py\example.py", line 2, in <module>
    import torchcraft as tc
ModuleNotFoundError: No module named 'torchcraft'

Help is appreciated!

**Comment by ChobitsTheZero** [comment]
> Been trying to run the python example, however when trying to run the script I recieve the following error.
> 
> C:\Users\EmilN>C:\Python\Python37-32\python.exe D:\AI\Starcraft\Starcraft2013\TorchCraft\examples\py\example.py -t IP
> Traceback (most recent call last):
> File "D:\AI\Starcraft\Starcraft2013\TorchCraft\examples\py\example.py", line 2, in 
> import torchcraft as tc
> ModuleNotFoundError: No module named 'torchcraft'
> 
> Help is appreciated!

**Comment by ChobitsTheZero** [comment]
Seems like I missed the part "Python setup: pip install pybind11 && pip install ."

My mistake, ops
